# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fbe2b2738d36d9751aaf968018291a8f47804a83bef0477567a425992630cd51441aded19da96844a3d7a542a8ba39a5d6cd55285356e9df7fed4af9a7d5da0

test:
  secret_key_base: 395e2f933f7ace0d4113ae59bfff0c77ff2a8f8db9637e56cf2a564a35cdfaad51f2bc052c17690d78c7e6e43e9e46a3c4accf65037fd86461053de58ea10472

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
